<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Address_aspect-square size-full</name>
   <tag></tag>
   <elementGuidId>7ddf7f5a-c127-42fe-a291-222559d93afa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-«r5»']/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>22c2e6ba-ccae-4f44-a27d-f3aec7e4d8e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>avatar-image</value>
      <webElementGuid>8264d68f-9e8e-4da5-86a5-9a5b6697b1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspect-square size-full</value>
      <webElementGuid>057376cb-ee91-43ca-b0aa-9aae39c0dad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>TeStAtHoN</value>
      <webElementGuid>521471b3-cec7-4843-8002-d899a4ae34eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/rmit.png</value>
      <webElementGuid>292a7c45-0705-44ea-980e-8b650aaf1fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-«r5»&quot;)/div[@class=&quot;flex items-center space-x-2 p-2&quot;]/span[@class=&quot;relative flex size-8 shrink-0 overflow-hidden rounded-full border-border cursor-pointer border transition-opacity hover:opacity-80&quot;]/img[@class=&quot;aspect-square size-full&quot;]</value>
      <webElementGuid>caa0cbb6-1b06-480a-b419-57d9ecdd86a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-«r5»']/div/span/img</value>
      <webElementGuid>257c046f-b943-40f4-97be-5a6835bbd9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='TeStAtHoN'])[2]</value>
      <webElementGuid>c0b87b6f-4a11-4b5e-b14a-a0dad0f2abd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/img</value>
      <webElementGuid>6952bbc7-691c-42f1-9d2e-8c7494f79e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'TeStAtHoN' and @src = '/rmit.png']</value>
      <webElementGuid>8457feac-f2a9-4afc-ab6f-d884606c9688</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
